version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $REPO_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
env:
  variables:
    REPO_URI: 'repo-URI' # dynamically loaded in the pipeline
    IMAGE_TAG: 'latest'  # Can dynamically change based on pipeline or versioning
