
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd cdk
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth --context stage=$STAGE_NAME
artifacts:
  files:
    - '**/*'  # Ensures the synthesized output is passed to the next phase
