version: 0.2

phases:
  install:
    commands:
      - cd cdk
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
      - cdk deploy --all --require-approval never
