version: 0.2

phases:
  install:
    commands:
      - echo "Installing Helm"
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - echo "Configuring kubectl"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo "Running Helm deployment"
      - helm upgrade --install my-frontend s3://$HELM_BUCKET_NAME/frontend-chart-0.1.0.tgz \
        --set image.repository=$REPO_URI \
        --set image.tag=$IMAGE_TAG \
        --set service.type=LoadBalancer \
        --namespace $NAMESPACE
artifacts:
  files:
    - '**/*'


