environments:
    - envName: dev
      account: "315730708373"
      region: "us-east-1"
    - envName: test
      account: "315730708373"
      region: "us-east-1"
    - envName: prod
      account: "315730708373"
      region: "us-east-1"