apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}  # The release name will come from Helm
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
